version: "3"
services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
    - ./data/pg:/var/lib/postgresql/data
  graphql:
    build: ./packages/wtop-server
    image: wtop-server
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
  nginx:
    build:
      context: ./packages/wtop-client
      args:
        - WTOP_HOSTNAME=${WTOP_HOSTNAME}
        - NODE_ENV=production
    image: wtop-client
    env_file: ./.env
    command: /bin/bash -c "envsubst '$WTOP_HOSTNAME' < /etc/nginx/conf.d/app.template > /etc/nginx/conf.d/app.conf && nginx -g 'daemon off;'"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
    depends_on:
      - db
      - graphql
    ports:
      - 127.0.0.1:8080:80
