version: "3"
services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
    - 5432:5432
    volumes:
    - ./data/pg:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    links:
     - db
    depends_on:
     - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    volumes:
     - ./data/pgadmin:/root/.pgadmin
    ports:
     - "5050:80"
