version: "3"
services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
    - ./data/pg:/var/lib/postgresql/data
  server:
    build: ./packages/wtop-server
    image: wtop-server
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
